risky: true

preset: laravel

version: 8

tab-width: 4

use-tabs: false

disabled:
  - concat_without_spaces
  - not_operator_with_successor_space

enabled:
  - is_null
  - phpdoc_property
  - logical_operators
  - concat_with_spaces
  - phpdoc_add_missing_param_annotation
