version: '3.7'
services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile-dev
    restart: unless-stopped
    volumes:
    - vendor-volume:/usr/src/app/vendor
    - .:/usr/src/app
    command:
    - bash
    - -c
    - |
      if [ ! -f "/usr/src/init" ]; then
        composer install
        php artisan key:generate
        php artisan migrate --seed
        chmod -R 777 storage
        touch /usr/src/init
      fi
      exec apache2-foreground
  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./docker/nginx:/etc/nginx/templates
    ports:
      - ${DOCKER_PORT}:80

volumes: 
  vendor-volume:
