openapi: 3.0.0
info:
  title: Silverbox API
  version: 1.1.0
  license:
    name: MIT

paths:
  /{client}:
    parameters:
      - name: client
        in: path
        required: true
        description: Client name
        schema:
          type: string
      - name: private
        in: query
        required: false
        schema:
          type: boolean
    post:
      summary: Upload a file
      operationId: file-upload
      tags:
        - Files
      security:
        - bearer: []
      responses:
        '201':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/File'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /{client}/{file}:
    parameters:
      - name: client
        in: path
        required: true
        description: Client name
        schema:
          type: string
      - name: file
        in: path
        required: true
        description: The id of the file to retrieve
        schema:
          type: string
    get:
      parameters:
        - name: h
          in: query
          required: false
          description: Height in px
          schema:
            type: number
        - name: w
          in: query
          required: false
          description: Width in px
          schema:
            type: number
      summary: Get a file
      operationId: file-get
      tags:
        - Files
      responses:
        '200':
          description: Binary file.
    patch:
      summary: Ability to change file path
      operationId: file-update
      tags:
        - Files
      security:
        - bearer: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - slug
              properties:
                slug:
                  description: 'New file name'
                  type: string
                  example: 'new-file-name'
      responses:
        '200':
          description: Info about file
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/File'
    delete:
      summary: Delete a file
      operationId: file-delete
      tags:
        - Files
      security:
        - bearer: []
      responses:
        '204':
          description: File successfully deleted.

  /{client}/{file}/info:
    parameters:
      - name: client
        in: path
        required: true
        description: Client name
        schema:
          type: string
      - name: file
        in: path
        required: true
        description: The id of the file to retrieve
        schema:
          type: string
    get:
      summary: File info
      operationId: file-info
      tags:
        - Files
      security:
        - bearer: []
      responses:
        '200':
          description: Info about file
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/File'

components:
  schemas:
    File:
      type: object
      properties:
        name:
          type: string
          example: '8BgXSCaMZae9auk1kVA9tRP2Km1CzvKsyE8ml8R0.jpg'
        owner:
          type: string
          example: 'client'
        visibility:
          type: string
          example: 'public'
        path:
          type: string
          example: 'client/8BgXSCaMZae9auk1kVA9tRP2Km1CzvKsyE8ml8R0.jpg'
        mime:
          type: string
          example: 'image/jpeg'
        size:
          type: number
          example: 142083
        lastModified:
          type: number
          example: 1640104826
    Error:
      type: object
      properties:
        message:
          type: string
          example: 'An error occurred.'
        code:
          type: number
          example: 500
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
