openapi: 3.0.0
info:
  title: Silverbox API
  version: 1.0.0
  license:
    name: MIT

paths:
  /{client}:
    parameters:
      - name: client
        in: path
        required: true
        description: Client name
        schema:
          type: string
      - name: private
        in: query
        required: false
        schema:
          type: boolean
    post:
      summary: Upload a file
      operationId: file-upload
      tags:
        - Files
      security:
        - bearer: []
      responses:
        '201':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/File'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /{client}/{file}:
    parameters:
      - name: client
        in: path
        required: true
        description: Client name
        schema:
          type: string
      - name: file
        in: path
        required: true
        description: The id of the file to retrieve
        schema:
          type: string
    get:
      parameters:
        - name: h
          in: query
          required: false
          description: Height in px
          schema:
            type: number
        - name: w
          in: query
          required: false
          description: Width in px
          schema:
            type: number
      summary: Get a file
      operationId: file-get
      tags:
        - Files
      responses:
        '200':
          description: Binary file.
    delete:
      summary: Delete a file
      operationId: file-delete
      tags:
        - Files
      security:
        - bearer: []
      responses:
        '204':
          description: File successfully deleted.

  /{client}/{file}/info:
    parameters:
      - name: client
        in: path
        required: true
        description: Client name
        schema:
          type: string
      - name: file
        in: path
        required: true
        description: The id of the file to retrieve
        schema:
          type: string
    get:
      summary: File info
      operationId: file-info
      tags:
        - Files
      security:
        - bearer: []
      responses:
        '200':
          description: Info about file
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/File'

components:
  schemas:
    File:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          example: '3e2S49ZlOoRqxcUJsK8qwNBbH9eGjSym'
        owner:
          type: string
          example: 'client'
        path:
          type: string
          example: 'client/3e2S49ZlOoRqxcUJsK8qwNBbH9eGjSym'
    Error:
      type: object
      properties:
        message:
          type: string
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
